### ISSUE TITLE
erreur de build pour la prod

### ISSUE THREAD

**Issue by akakeronos** [datalocale/dataviz-finances-gironde#495]
J'ai une erreur à l'exécution de la commande npm run build-production

J'ai fait un npm install avant mais je vois que la version de node.js est toujours 5.6.
Est-ce que je dois faire quelque chose sur mon environnement local ?

log : 

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build-production' ]
2 info using npm@5.6.0
3 info using node@v8.10.0
4 verbose run-script [ 'prebuild-production',
4 verbose run-script   'build-production',
4 verbose run-script   'postbuild-production' ]
5 info lifecycle dataviz-gironde@1.0.0~prebuild-production: dataviz-gironde@1.0.0
6 info lifecycle dataviz-gironde@1.0.0~build-production: dataviz-gironde@1.0.0
7 verbose lifecycle dataviz-gironde@1.0.0~build-production: unsafe-perm in lifecycle true
8 verbose lifecycle dataviz-gironde@1.0.0~build-production: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\github\dataviz-finances-gironde\node_modules\.bin;C:\Users\pascal romain\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\pascal romain\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files\nodejs;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Program Files (x86)\NoteBook FanControl;C:\Program Files (x86)\Yarn\bin;C:\Program Files\PuTTY;D:\python27;C:\msys64;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit;C:\Ruby25-x64\bin;C:\Users\pascal romain\AppData\Local\Microsoft\WindowsApps;C:\Users\pascal romain\AppData\Roaming\npm;C:\Users\pascal romain\AppData\Local\atom\bin;C:\Users\pascal romain\AppData\Local\Yarn\bin;D:\python27;C:\Program Files\Microsoft VS Code\bin;C:\Users\pascal romain\AppData\Local\Keybase;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
9 verbose lifecycle dataviz-gironde@1.0.0~build-production: CWD: D:\github\dataviz-finances-gironde
10 silly lifecycle dataviz-gironde@1.0.0~build-production: Args: [ '/d /s /c',
10 silly lifecycle   'cross-env GIRONDE_FR_DRUPAL_MEDIA_ID=2459 npm run build-gironde-fr:public' ]
11 silly lifecycle dataviz-gironde@1.0.0~build-production: Returned: code: 1  signal: null
12 info lifecycle dataviz-gironde@1.0.0~build-production: Failed to exec build-production script
13 verbose stack Error: dataviz-gironde@1.0.0 build-production: `cross-env GIRONDE_FR_DRUPAL_MEDIA_ID=2459 npm run build-gironde-fr:public`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid dataviz-gironde@1.0.0
15 verbose cwd D:\github\dataviz-finances-gironde
16 verbose Windows_NT 10.0.16299
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build-production"
18 verbose node v8.10.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error dataviz-gironde@1.0.0 build-production: `cross-env GIRONDE_FR_DRUPAL_MEDIA_ID=2459 npm run build-gironde-fr:public`
22 error Exit status 1
23 error Failed at the dataviz-gironde@1.0.0 build-production script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by thom4parisot** [comment]
Ma première tentative sur une install fraiche avec Node@8 et npm@5.6 semble rouler.

À tout hasard, supprime le répertoire `node_modules`, fais `npm install` et retente ensuite `npm run build-production`.

Si ça marche pas y'a un truc qui cloche spécifique à Windows.

**Comment by akakeronos** [comment]
pas mieux... je vais tenter de désinstaller node

**Comment by akakeronos** [comment]
pas mieux...

Je ne comprends pas cette erreur 

**FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory**


 1: node_module_register
 2: v8::internal::FatalProcessOutOfMemory
 3: v8::internal::FatalProcessOutOfMemory
 4: v8::internal::Factory::NewCodeRaw
 5: v8::internal::Factory::NewCode
 6: v8::internal::modulo

**Comment by akakeronos** [comment]
node 8.11.3
npm 5.6

**Comment by thom4parisot** [comment]
Ce que j'en comprends c'est que le script Node est à cours de mémoire pendant qu'il fait ses trucs. Du coup ça plante.

Ça m'étonne un peu mais si t'as plein de trucs qui tournent sur ton ordi (ou une bonne appli gourmande) ça empêche peut-être une opération gourmande dans le script de build.

**Comment by akakeronos** [comment]
c'est bon après un autre npm install ça build
