### ISSUE TITLE
Packages introuvables

### ISSUE THREAD

**Issue by VictorVila** [datalocale/dataviz-finances-gironde#534]
Bonjour,
Votre projet nous semble très intéressant. Afin de l'essayer avec un autre jeu de données, nous avons cloné le dépôt, mais dès qu'on lance `npm install`, on a des problèmes (extrait du log) :

`17735 timing action:extract Completed in 21946ms`
`17736 warn tar ENOENT: no such file or directory, open 'C:\www\dataviz-finances-gironde\node_modules\.staging\core-js-87d22566\fn\_.js'`
`17737 warn tar ENOENT: no such file or directory, open 'C:\www\dataviz-finances-gironde\node_modules\.staging\babel-runtime-15d2dd9f\core-js\symbol\async-iterator.js'`
`17738 warn tar ENOENT: no such file or directory, open 'C:\www\dataviz-finances-gironde\node_modules\.staging\babel-runtime-15d2dd9f\core-js\symbol\iterator.js'`
`17739 warn tar ENOENT: no such file or directory, open 'C:\www\dataviz-finances-gironde\node_modules\.staging\babel-runtime-15d2dd9f\core-js\symbol\key-for.js'`
`17740 warn tar ENOENT: no such file or directory, open 'C:\www\dataviz-finances-gironde\node_modules\.staging\babel-runtime-15d2dd9f\core-js\symbol\match.js'`
`...`
`...`
(quelques 200 lignes).

Des pistes sur ce qu'il faudrait faire ?

Merci et bonne journée.

**Comment by thom4parisot** [comment]
@VictorVila et bonjour !

Qu'affichent les sorties des commandes `npm version` et `node version` ?

Par curiosité, tu essaies avec les données de quelle collectivité ?

**Comment by VictorVila** [comment]
Bonjour @oncletom merci pour ta réponse !

J'ai ces versions : 

* `node' : 8.12.0
* `npm` : 6.4.1

Pour le test on allait utiliser les données de la Communauté Urbaine Creusot Montceau. Mais l'idée serait de le mettre à disposition d'autres collectivités de Bourgogne Franche Comté.

**Comment by DavidBruant** [comment]
Salut @VictorVila, [a priori](https://travis-ci.org/datalocale/dataviz-finances-gironde/jobs/554758662#L440), ça marche bien avec Node 12. Est-ce que c'est possible pour toi d'upgrader ta version de Node ? Si c'est pas possible, je peux regarder le problème avec Node 8

**Comment by VictorVila** [comment]
Salut @DavidBruant , oui je dois pouvoir l'upgrader. 
Je vous tiens au courant la semaine prochaine.
Merci et bon we !

**Comment by VictorVila** [comment]
Bonjour,
Merci pour l'information, avec node v 12 j'ai presque complété `npm install`. Il y a eu juste eu un WARN car il a skippé fsevents `Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin"`

Au lancement de npm watch, j'ai eu 3 soucis  : 
1) 
`> dataviz-gironde@1.0.0 prepare:plan-de-compte C:\www\dataviz-finances-gironde`
`> plans-de-compte --in data/finances/CA --out data/finances/plansDeCompte`
`in data/finances/CA out data/finances/plansDeCompte`
`Fichiers <DocumentBudgetaire> trouvés dans le dossier data/finances/CA :`
`(node:10068) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "from" ``argument must be of type string. Received type undefined`
`   at validateString (internal/validators.js:107:11)`
`    at relative (path.js:434:5)`
`    at C:\www\dataviz-finances-gironde\node_modules\plans-de-compte\bin\plans-de-compte.js:66:52`
`    at Array.map (<anonymous>)`
`    at C:\www\dataviz-finances-gironde\node_modules\plans-de-compte\bin\plans-de-compte.js:66:38`
`    at async Promise.all (index 0)`

2) Cette erreur enchaine avec un souci concernant memoized : 
`> dataviz-gironde@1.0.0 build:public:data:m52-strings C:\www\dataviz-finances-gironde`
`> node -r esm tools/make-doc-budg-strings.js`
`Error: Cannot find module '../../../shared/js/finance/memoized' from 'C:\www\dataviz-finances-gironde\src\m52-overview\js\components'`

3) Puis un autre concernant m52-strings : 
`> dataviz-gironde@1.0.0 watch:public:style C:\www\dataviz-finances-gironde`
`> node-sass --importer src/public/style/env-importer.js --watch src/public/style/main.scss build/public.css`
`Error: Cannot find module '../../../build/finances/m52-strings.json' from 'C:\www\dataviz-finances-gironde\src\public\js'`

Si vous avez des pistes je suis preneur. Merci.

**Comment by DavidBruant** [comment]
> Il y a eu juste eu un WARN car il a skippé fsevents Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin"}

Je l'ai aussi sur Linux. On peut l'ignorer sans problème

> Au lancement de npm watch

Le dépôt est actuellement et temporairement dans un état intermédiaire avec du code inutilisé. Il y a une [tâche pour l'enlever](https://github.com/datalocale/dataviz-finances-gironde/issues/527). En attendant, `npm watch` ne fonctionne pas vraiment (parce que `watch:m52overview` ne marche plus). Seulement `npm watch:public` est pertinent.
#527 devrait être corrigé prochainement

> plans-de-compte --in data/finances/CA --out data/finances/plansDeCompte
in data/finances/CA out data/finances/plansDeCompte
> TypeError [ERR_INVALID_ARG_TYPE]: The "from" ``argument must be of type string. Received type undefined

hmm... J'ai l'impression que le problème est [ici](https://github.com/dtc-innovation/plans-de-compte/blob/43d11e3ff817577031a1c651d29a7ee221b0fdb4/bin/plans-de-compte.js#L66) et dû à la variable d'environnement `PWD` qui n'existe pas sur Windows (tu es bien sur Windows ?)

Je peux regarder à corriger ce problème la semaine prochaine, mais je n'ai pas de Windows et donc ça sera un peu à l'aveugle.


> Error: Cannot find module '../../../shared/js/finance/memoized' from 'C:\www\dataviz-finances-gironde\src\m52-overview\js\components'

Cette erreur ne concerne que `npm run watch:m52overview` et n'aura pas lieu si tu fais `npm watch:public`


> Error: Cannot find module '../../../build/finances/m52-strings.json' from 'C:\www\dataviz-finances-gironde\src\public\js'

Ce problème sera réglé dans la foulée de la correction du problème sur `plans-de-compte` qui génère le fichier `m52-strings.json`

**Comment by VictorVila** [comment]
Merci pour tes réponses @DavidBruant ,
En effet, j'ai une machine windows au travail, mais je dois pouvoir trouver un poste avec Linux. Ce n'est peut-être pas la peine d'adapter à windows.

**Comment by thom4parisot** [comment]
@VictorVila salut ! J'ai proposé un changement au script de téléchargement des plans de compte. Dis-moi si ça t'emmène vers quelque chose de plus fonctionnel !

**Comment by VictorVila** [comment]
@oncletom Bonjour
Merci pour la nouvelle. Je vais faire un test fin de semaine prochaine et je te tiens au courant.
Bonne journée !

**Comment by thom4parisot** [comment]
@VictorVila dac ça roule. À dispo pour t'aiguiller et t'aider à naviguer les problèmes que tu rencontres.
